### ISSUE TITLE
The 'view source' links in the module ExDocs reference a filesystem path

### ISSUE THREAD

**Issue by linusdm** [elixir-cldr/cldr_plugs#1]
The 'view source' (`</ >`) links in the module docs (e.g. https://hexdocs.pm/ex_cldr_plugs/Cldr.Plug.SetLocale.html) refer to a local filesystem path.

`https://github.com/elixir-cldr/cldr_plugs/blob/v1.0.0//Users/kip/Development/cldr_plug/lib/cldr/plug/plug_set_locale.ex#L1`

**Comment by kipcole9** [comment]
@linusdm my apologies, somehow I wasn't notified when you raised this issue. I'll check into it ASAP. Thanks very much for raising the issue.

**Comment by kipcole9** [comment]
I have removed the unnecessary conditional compilation in commit [426eb11](https://github.com/elixir-cldr/cldr_plugs/commit/426eb111fa3fd4fc247930518cee7bd3d29c8122).

I have a few more items to work on but expect to publish a new version this weekend.  Thanks again for the report. The changelog entry reads:

### Bug Fixes

* Fix setting the locale from the result returned from an `{M, f}` or `{M, f, [a]}`. Thanks to @rubas for the PR.

* Don't make modules `Cldr.Plug.AcceptLanguage` and `Cldr.Plug.PutSession` dependent on `Plug`, `Plug` is a required dependency since this library was split from `ex_cldr`. Thanks to @linusdm for the report. Closes #1.

**Comment by linusdm** [comment]
No worries @kipcole9! Thanks for fixing the issue 🚀
